### ISSUE TITLE
It is possible to change the backlight by software?

### ISSUE THREAD

**Issue by Mte90** [slimbook/keyboard#1]
From the readme is not clear if just on install and not on runtime.

**Comment by slimbook** [comment]
Hi!
we will do it in the future. 
Thanks

**Comment by Mte90** [comment]
there are any plans for this project? As it is not getting real changes since 6 months.

**Comment by alejandrobyte** [comment]
oh, yes, it will not take more than 2 months.
thanks

**Comment by slimbook** [comment]
oh, yes, it will not take more than 2 months.
thanks

**Comment by Mte90** [comment]
It is confirmed for the next month?

**Comment by slimbook** [comment]
Hi @Mte90 
Try the new app:
sudo add-apt-repository ppa:slimbook/slimbook
sudo apt install slimbookrgbkeyboard

I await your feedback :)

**Comment by Mte90** [comment]
I installed with the bash script as i am on debian but how works? there are no instructions...

**Comment by abyte20** [comment]
mmm, can you add the repo and key?
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BE80F1EEB3838E61E42091B378A22399981017FC
regards

**Comment by slimbook** [comment]
mmm, can you add the repo and key?
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BE80F1EEB3838E61E42091B378A22399981017FC
regards

**Comment by Mte90** [comment]
so the install by bash is not required?
Can you update the readme?

Also I am on KDE so looking at the code there is only a gnome extension.

**Comment by slimbook** [comment]
Hi,
No, the new package can be run on KDE, without Gnome Extension, but we need some days for try well.

**Comment by Mte90** [comment]
I can wait but just add this information in the readme? also for the cli usage of the module not just how to install?

**Comment by slimbook** [comment]
You can test yourself and contribute. Your help or pull request would be great.

**Comment by Mte90** [comment]
Yes of course if I have an idea how works.
Looking at the files as it is not explained if there is a cli tool or works by parameters I found this https://github.com/slimbook/keyboard/blob/main/backlight/titan/qc71_laptop/README.md
So works with settings on the fly for the kernel.
