### ISSUE TITLE
Cannot donwload slimbookrgbkeyboard

### ISSUE THREAD

**Issue by ficast** [slimbook/keyboard#2]
I'm not beeing able to install slimbookrgbkeyboard, is that repository down?

```
▶   sudo apt-get install slimbookrgbkeyboard

Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
E: Impossível encontrar o pacote slimbookrgbkeyboard
(base) 
~      
```

**Comment by slimbook** [comment]
Are you using 22.04? In that case Slimbook RGB Keyboard will be available soon, sorry for the delay but some changes are being made.

**Comment by ficast** [comment]
That's correct @slimbook ! Using popOS 22.04

**Comment by slimbook** [comment]
It has been uploaded to jammy release
