### ISSUE TITLE
Slimbook TITAN lightbar doesn't work with latest kernel 6.2.7

### ISSUE THREAD

**Issue by aliquo93** [slimbook/keyboard#4]
As the title says, please update Slimbook RGB to make it compatible with the latest kernel. Thanks!

**Comment by MarSlimbook** [comment]
Are you using Ubuntu?
In that case, you should be able to install [this module](https://github.com/Slimbook-Team/slimbook-qc71-dkms) from our launchpad repository, reinstalling this dependency together with the app should fix the problem, if there is any problem, provide a log launching app from terminal.

**Comment by aliquo93** [comment]
I'm on Kubuntu, will try.

Cordiali saluti,

Daniele Aliquò

**Comment by Lt-Henry** [comment]
I am going to close this because it is already fixed. Feel free to re-open if problem persists.
